# NeoPixel library for CircuitPython
# This is a stub file to allow import; actual library must be present on device for real use.
class NeoPixel:
    def __init__(self, pin, n, brightness=1.0, auto_write=True): ...
    def fill(self, color): ...
    def show(self): ...
    def __setitem__(self, index, color): ...
    def __getitem__(self, index): ...

